services:
    randock.abstract.visa_center_api_client:
        abstract: true
        public: true
        arguments:
            - "%randock_visa_center_api.base_uri%"
            - "%randock_visa_center_api.version%"
            - "%randock_visa_center_api.auth%"

    randock.visa_center_api.order_client:
        class: Randock\VisaCenterApi\Client\OrderClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.transaction_client:
        class: Randock\VisaCenterApi\Client\TransactionClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.visa_type_client:
        class: Randock\VisaCenterApi\Client\VisaTypeClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.traveler_client:
        class: Randock\VisaCenterApi\Client\TravelerClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.file_client:
        class: Randock\VisaCenterApi\Client\FileClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.notification:
        class: Randock\VisaCenterApi\Client\NotificationClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.province:
        class: Randock\VisaCenterApi\Client\ProvinceClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.order_issue:
        class: Randock\VisaCenterApi\Client\OrderIssueClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.invoice:
        class: Randock\VisaCenterApi\Client\InvoiceClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.queue_client:
        class: Randock\VisaCenterApi\Client\QueueClient
        parent: randock.abstract.visa_center_api_client

    randock.visa_center_api.document_client:
        class: Randock\VisaCenterApi\Client\DocumentClient
        parent: randock.abstract.visa_center_api_client